# Generated by Django 5.2.6 on 2025-09-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='word_en',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
